### ISSUE TITLE
It only works with NLog 4.5.0-alpha2

### ISSUE THREAD

**Issue by feugen24** [datalust/nlog-targets-seq#11]
Hi,
I am testing on vs2015 on a simple project and it works but if i update NLog 
NLog 4.5.0-alpha2 -> NLog 4.5.0-alpha3
or NLog 4.5.0-alpha2 -> NLog 5.0.0-beta5 
nothing is logged in seq. Code:

```
       
 logger.Info("Hello, {Server}, from {Library}", server, library);

 // Text logging: the two properties are captured using positional arguments:
 logger.Info("Goodbye, {0}, from {1}", server, library);
```

**Comment by nblumhardt** [comment]
Thanks @feugen24 - NLog 4.5 is introducing new APIs which are changing between the various alphas. I'll update this to `alpha3` shortly; there won't be support for 5.x until the new APIs are ported forwards.
