### ISSUE TITLE
Pre-render tokens with format specifiers

### ISSUE THREAD

**Issue by nblumhardt** [datalust/nlog-targets-seq#2]
https://github.com/datalust/nlog-targets-seq/blob/dev/src/NLog.Targets.Seq/LogEventInfoFormatter.cs#L72

So that the message template can be accurately rendered on the remote machine, any formatted tokens in the message template need to be pre-rendered.

E.g.:

```csharp
logger.Info("The number is {N:000.00}", 42);
```

Here we want to retrieve the format `000.00` associated with the `N` property.

@304NotModified any clue how this can be achieved?

**Comment by 304NotModified** [comment]
is this with NLog 4.5? 

The format specifier is not stored public. Is this needed?

**Comment by 304NotModified** [comment]
is this an issue as this issue is closed?

**Comment by nblumhardt** [comment]
Sorry @304NotModified - had some time blocked out yesterday so kept pushing forward.

The target is working now, but it's doing that by re-parsing the message template (https://github.com/datalust/nlog-targets-seq/blob/dev/src/NLog.Targets.Seq/LogEventInfoFormatter.cs#L83) which isn't ideal (if the template already needs to be parsed once by the framework.

Shall I open an issue on the NLog repo to discuss?

**Comment by 304NotModified** [comment]
> Shall I open an issue on the NLog repo to discuss?

Yes please. Re-parse is indeed not intended :) Great to have this feedback so early!
