### ISSUE TITLE
Include GDC/MDC/MDLC/NDC data in events

### ISSUE THREAD

**Issue by nblumhardt** [datalust/nlog-targets-seq#24]

**Comment by snakefoot** [comment]
This should be done by using JsonLayout. This will ensure that it will still work when using async-wrapper.

**Comment by nblumhardt** [comment]
Thanks for the advice, @snakefoot 👍

**Comment by nblumhardt** [comment]
@snakefoot just coming back around to this - a couple of questions in case you have a moment to offer some pointers :-)

I've started looking at how to get `JsonLayout` to produce the format we need, via its properties and `JsonAttribute`:

* Do we need to register the layout somehow, or is it enough just to embed one in the `SeqTarget` class as a private field and just call `RenderLogEvent()` with it when formatting out the events? (Mostly concerned with async-wrapper functionality here)
* It doesn't seem like we can conditionally include properties (`JsonAttribute`s), e.g. the exception property or [message vs. template](https://github.com/datalust/nlog-targets-seq/blob/dev/src/NLog.Targets.Seq/LogEventInfoFormatter.cs#L50) - is subclassing `JsonLayout` the best way to achieve this?
* Is there currently any way to access the un-formatted message (i.e. the template) through a `SimpleLayout`? I've spotted `${message}` - ideally we'd use `${template}` or similar for message templates

Really only just starting to wrap my head around NLog's internals, as you can tell :-) Cheers!

**Comment by snakefoot** [comment]
> Do we need to register the layout somehow, or is it enough just to embed one in the SeqTarget class 

It needs to be visible as a public member-property on the target, for it to be fully recognized by the NLog-engine.

> It doesn't seem like we can conditionally include properties 

It is possible to include custom properties using the JsonLayout-attributes. Where one can register custom Layout-implementations.

>  Is there currently any way to access the un-formatted message 

Yes the ${message}-layout has a raw-property: https://github.com/NLog/NLog/wiki/Message-Layout-Renderer

Seq is not the first custom NLog target, that tries to access the NLog-context, and most fails as soon they are wrapped in the asyncwrapper (or other buffering/batching-wrapper).

I'm trying to get a PR approved for NLog 4.5, that will make the access to the NLog-context-properties a little easier for custom-targets, as not all custom targets are depending on JSON:

https://github.com/NLog/NLog/pull/2467

Then you will not have to fiddle with the JsonLayout to capture the NLog-contest.

It is still review-in-progress, and pretty much written out of thin-air after having looked at several custom NLog-targets and seeing how they fail to handle NLog-context. You are very welcome to take a look at the protected/public-methods of the [TargetWithContext](https://github.com/snakefoot/NLog/blob/7fefb7b4ae70893a22b8b7ba1116d582710fc121/src/NLog/Targets/TargetWithContext.cs) to see if it captures your needs. There is a little hurdle that is hard for me to solve, which is the serialization of complex-context-properties, as this has to be handled by the custom-target, that needs to convert to their own internal format (See `SerializeItemValue`)

**Comment by nblumhardt** [comment]
Thank you, Rolf! I'll investigate those points.

Best regards,
Nick

**Comment by nblumhardt** [comment]
I've made some progress down the `JsonLayout` route - one problem remaining:

```csharp
log.Info("Some {Item}", new[] { Prop = 42 })
```

This event seems like it should carry a to-string representation of `Item`, since the `@` character is not specified in the template. But, `JsonLayout` serializes the property as structured data.

Is this a bug I should raise, @jods4? Cheers!

**Comment by nblumhardt** [comment]
MDC and MDLC are now working via `JsonLayout`.

GDC and NDC are not included - there doesn't appear to be a `JsonLayout` property to include them. Will investigate further.

**Comment by nblumhardt** [comment]
I think we'll be happy with the properties included in JsonLayout and not reinvent the wheel here; will reconsider GDC if anyone puts this forward as a need. Cheers!
