### ISSUE TITLE
Add an attribute in property tag to indicate passed value is json

### ISSUE THREAD

**Issue by nareshpatel** [datalust/nlog-targets-seq#25]
I am using NLog and currently using a custom layout renderer to convert all properties to json to file based on following [SO answer](https://stackoverflow.com/questions/44048187/layout-nlog-properties-as-json).
setup works properly for File target where json gets serialized 

and I have following setup for NLog.Targets.Seq

```
<target name="seq" xsi:type="Seq" serverUrl="http://localhost:5341">
<property name ='properties' value='${json-event-properties}'/>
</target>
```

this gets sent as string instead of a json object to seq.
I verified it by downloading Raw Json from Seq.

I think adding an attribute to let Nlog.Targets.Seq know that passed string is json and making necessary changes in the nuget will help resolve the issue.
e.g. 

```
<target name="seq" xsi:type="Seq" serverUrl="http://localhost:5341">
<property name ='properties' value='${json-event-properties}' isJson=true/>
</target>
```

**Comment by nblumhardt** [comment]
Hi Naresh, thanks for the post. Won't the Seq sink already include these properties as top-level properties on the log event? (Perhaps #24 is preventing this?)

Best regards,
Nick
