### ISSUE TITLE
Collections aren't being logged in NLog 4.5 RTM

### ISSUE THREAD

**Issue by kevinmcfarlane** [datalust/nlog-targets-seq#30]
I just tried the examples here without explicitly fiddling with layout.

https://github.com/nlog/nlog/wiki/How-to-use-structured-logging 

They all log as expected to file but for Seq the collection examples just output type names, e.g., Test System.String[] instead of Test "a", "b."

```
logger.Info("Test {value1}", new List<string> { "a", "b" }); // list of strings. Result: Test "a", "b"
logger.Info("Test {value1}", new[] { "a", "b" }); // array. Result: Test "a", "b"
logger.Info("Test {value1}", new Dictionary<string, int> { { "key1", 1 }, { "key2", 2 } }); // dict. Result:  Test "key1"=1, "key2"=2
```

I notice that Seq.Client.NLog is Oct 9th, so is that an issue?

**Comment by nblumhardt** [comment]
Hi Kevin, thanks for getting in touch.

It sounds like you're using _Seq.Client.NLog_ - from NLog 4.5, you'll need the _NLog.Targets.Seq_ package, instead.

Does this sort it out?

Best regards,
Nick

**Comment by kevinmcfarlane** [comment]
Hi Nick, yes I'd opened an old test console application that was still referencing Seq.Client.NLog and I just upgraded NLog to 4.5 with no other changes.

The new package is working, although it outputs in JSON format regardless of {value1} or {@value1}. is that intentional? I.e., for list and array I get `Test ["a", "b"]` in both cases.

**Comment by nblumhardt** [comment]
Hi @kevinmcfarlane; for arrays, I believe elements will always be (shallow-) captured by default. If you pass a complex object, or want to serialize the elements within an array, the `@` should be required (this is how Serilog works, anyway). Let me know if you're observing different behavior.

**Comment by kevinmcfarlane** [comment]
Hi Nick, what I was finding was that, when writing to Seq (but not when writing to file) I got the same output whether I used the @ or not.

**Comment by nblumhardt** [comment]
Thanks for the follow-up 👍

What you've described was the case in some of the NLog 4.5 RCs, but in 4.5.0 RTM with NLog.Targets.Seq 1.0.0, I get what I think are correct results:

![image](https://user-images.githubusercontent.com/342712/38281477-17be1c9e-37ee-11e8-8e75-92b7dce7e107.png)


The top event has an `@User` token in the message template, while the one below is just `User`.

Any ideas how we can narrow it down?

**Comment by kevinmcfarlane** [comment]
Hi Nick, it works OK with objects. It is just arrays, lists and dictionaries where I'm seeing no difference in behaviour. If you refer to the examples section here https://github.com/nlog/nlog/wiki/How-to-use-structured-logging.

```
logger.Info("Test {value1}", new List<string> { "a", "b" }); // list of strings. Result: Test "a", "b"
logger.Info("Test {value1}", new[] { "a", "b" }); // array. Result: Test "a", "b"
logger.Info("Test {value1}", new Dictionary<string, int> { { "key1", 1 }, { "key2", 2 } }); // dict. Result:  Test "key1"=1, "key2"=2
```


I don't get the results as described here. I always get the @value1 version, e.g., Test ["a", "b"] instead of Test "a", "b" as above.

But writing to file does distinguish between value1 and @value1, as expected.

I assume Serilog itself does work as expected, though I've not done a test yet.

**Comment by nblumhardt** [comment]
Thanks for the additional detail. I think this is as intended - there may be a few more collection types other than arrays that are shallow-captured by default.

In the case of this target, it's using the built-in JSON formatter from NLog, so not something directly addressable here. It doesn't seem like any changes are needed, but for some background, https://github.com/NLog/NLog/issues/2557 has some discussion of the behaviour.

HTH!

**Comment by kevinmcfarlane** [comment]
Thanks, that clears things up. I'll close this now.
