### ISSUE TITLE
`@m` is message template in stead of message?

### ISSUE THREAD

**Issue by furier** [datalust/nlog-targets-seq#31]
![image](https://user-images.githubusercontent.com/776919/38418417-9b01cbb4-399c-11e8-9e73-32335c1c17f5.png)

```json
{
  "@t": "2018-04-06T10:52:17.2967668Z",
  "@mt": "Removed sequence entry for Job: {Job.Id} as it completed with the state: {Job.State}.",
  "@m": "Removed sequence entry for Job: {Job.Id} as it completed with the state: {Job.State}.",
  "@i": "5f2536b7",
  "@l": "Debug",
  "MachineName": "XXX",
  "SiteName": "XXX",
  "Logged": "2018/04/06 12:52:17.296",
  "Level": "Debug",
  "Solution": "XXX",
  "Message": "Removed sequence entry for Job: \"223234\" as it completed with the state: \"Deleted\".",
  "Logger": "CleanupSequenceJobFilterAttribute",
  "Properties": "Job.Id=223234|Job.State=Deleted",
  "Https": "false",
  "RemoteAddress": ": - ",
  "Callsite": "CleanupSequenceJobFilterAttribute.OnStateApplied",
  "Job.Id": "223234",
  "Job.State": "Deleted"
}
```

Shouldn't `@m` be the value in the `Message` and not the MessageTemplate aka `@mt` ? Dont know if this is a log target issue or a configuration issue either in seq or with nlog?

**Comment by furier** [comment]
Looks like something is having problems with the `.` dot in the variable names, because variable names without dots are rendered correctly.

```json
{
  "@t": "2018-04-06T11:35:19.6885535Z",
  "@mt": "{NotificationHandler}.Recieved: {Notification.Type} {@Notification.Value}",
  "@m": "ApplicationUpdatedNotificationHandler.Recieved: {Notification.Type} {@Notification.Value}",
  "@i": "e1ee5e6a",
  "@l": "Debug",
  "MachineName": "XXX",
  "SiteName": "XXX",
  "Logged": "2018/04/06 13:35:19.688",
  "Level": "Debug",
  "Solution": "XXX",
  "Message": "\"ApplicationUpdatedNotificationHandler\".Recieved: \"EntityUpdatedNotification\" {\"Id\":\"5ecb14ea-2a9d-4c9b-8fe7-938f4ddd9123\", \"EntityType\":\"IN.ServiceLayer.ApplicationDbHandler.DataModels.Application\"}",
  "Logger": "XXX",
  "Properties": "NotificationHandler=ApplicationUpdatedNotificationHandler|Notification.Type=EntityUpdatedNotification|Notification.Value=EntityType: Application, Id: 5ecb14ea-2a9d-4c9b-8fe7-938f4ddd9123",
  "Https": "false",
  "RemoteAddress": ": - ",
  "Callsite": "EntityNotificationHandlerBase`2.Handle",
  "NotificationHandler": "ApplicationUpdatedNotificationHandler",
  "Notification.Type": "EntityUpdatedNotification",
  "Notification.Value": {
    "Id": "5ecb14ea-2a9d-4c9b-8fe7-938f4ddd9123",
    "EntityType": "Application"
  }
}
```

**Comment by nblumhardt** [comment]
Thanks for the note!

Dots aren't valid in message template property names - [`Name ::= [0-9A-z_]+`](https://messagetemplates.org/) - NLog might be a bit more permissive than Serilog here.

On the Seq side, if you've collected events like this, you can escape and query them with:

```sql
@Properties['Job.Id'] = '223234'
```

There are some interesting considerations around dotted property names; the main reason loggers like NLog and Serilog don't map properties like `Job.Id` and `Job.State` onto JSON objects like `"Job": {"Id": "223234", "State": "Deleted"}` is that it's complex and expensive to do it well. Still something that might be possible in the future though, hence the restriction on using dots in property names as things stand today.

If you want to keep the `Job` nesting, your event could be written as:

```csharp
logger.Info("Removed sequence entry for completed job {@Job}", new { job.Id, job.State });
```

Otherwise, condensing the names is needed:

```csharp
logger.Info("Removed sequence entry for Job: {JobId} as it completed with the state: {JobState}", job.Id, job.State);
```

HTH,
Nick

**Comment by furier** [comment]
Hi Nick.

Thank you for a well written and explained response, it makes sense and maybe it can be done in the future without too much performance penalties.

Not sure if there is any documentation describing this limitation around tho, and if it doesn't it would be a nice addition, like a gotcha section or something. :) If it belongs here, in the Seq-NLog documentation or in NLog's own documentation I'm not sure. Maybe in the Seq documentation?

BR Sander

**Comment by nblumhardt** [comment]
Thanks for the follow-up! I think the best outcome would be for everyone to link to messagetemplates.org (Serilog, NLog, Seq and others), and to improve the docs over there to make this clearer (apart from reading the grammar).

There's a repository at https://github.com/messagetemplates/messagetemplates.org, in case anyone reading this decides to have a shot :-)

Cheers!
