### ISSUE TITLE
Update Seq documentation for NLog

### ISSUE THREAD

**Issue by snakefoot** [datalust/nlog-targets-seq#35]
@nblumhardt  I guess NLog has come out of alpha stage, and the documentation can be updated too:

https://docs.getseq.net/docs/using-nlog

**Comment by nblumhardt** [comment]
Thanks Rolf! The v5 docs were updated, I've now copied those back to the 4.2 (current) docs: https://docs.getseq.net/v4.2/docs/using-nlog
