### ISSUE TITLE
Missing example of configuration from appsettings.json

### ISSUE THREAD

**Issue by sebastianstudniczek** [datalust/nlog-targets-seq#56]
There is an option to configure NLog from appsettings.json instead of NLog.config, so I guess it will be really usefull to provide some example in README on how to configure properly Seq target with properties.

**Comment by sebastianstudniczek** [comment]
Great, thank for quick response !

**Comment by snakefoot** [comment]
@jbennink Thank you for the feedback (And you are right, that the names comes from NLog-default-behavior). Created #58
