### ISSUE TITLE
Compatibility with NLog 5.0.0

### ISSUE THREAD

**Issue by jbennink** [datalust/nlog-targets-seq#59]
After upgrading NLog to 5.0.0 and NLog.Extensions.Logging to 5.0.0 the Seq target does not work anymore. I get an exception on:

NLogConfigurationException: Failed to create Target of type: Seq
NLog.Config.LoggingConfigurationParser.FactoryCreateInstance<T>(string classType, INamedItemFactory<T, Type> factory)

I am using the default appsettings.json configuration as shown in the documentation for this package. 

I did see in the breaking changes for NLog 5.0.0 that they changes some properties (such as `bufferSize` and `flushTimeout` from int to Layout<int> in this commit part of changes to the BufferWrapper feature also used by this packages, see PR/Commit: https://github.com/NLog/NLog/pull/4858/files 

The NLog 4.7.14 and NLog.Extensions.Logging 1.7.4 I was using in combination with NLog.Targets.Seq 2.1.0 does work. This prevents upgrading to NLog 5.0.0

**Comment by snakefoot** [comment]
Think you are seeing this breaking change: [NLog Extensions assemblies will not load automatically](https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html#nlog-extensions-assemblies-will-not-load-automatically)

The solution is to update the NLog.config to include:

```xml
  <extensions>
    <add assembly="NLog.Targets.Seq"/>
  </extensions>
```

Or use the new feature in NLog v5 to include extension-assembly in type-alias:
```xml
  <target xsi:type="Seq, NLog.Targets.Seq" serverUrl="http://localhost:5341" apiKey="">
    <property name="ThreadId" value="${threadid}" as="number" />
  </target>
```

**Comment by jbennink** [comment]
Yep that fixed the issue, thanks @snakefoot
