### ISSUE TITLE
could not work with nlog5.0x

### ISSUE THREAD

**Issue by gwnpeter** [datalust/nlog-targets-seq#64]
could not work with nlog5.0x
it is good with nlog4.7.15

version:
NLog.Targets.Seq V2.10 
net4.72 / net6.0
Seq 2021.4

**Comment by snakefoot** [comment]
Duplicate of #59 ?

**Comment by gwnpeter** [comment]
Duplicate of https://github.com/datalust/nlog-targets-seq/issues/59#issuecomment-1137510375
fixed！

**Comment by gwnpeter** [comment]
Duplicate of https://github.com/datalust/nlog-targets-seq/issues/59#issuecomment-1137510375
fixed！

**Comment by gwnpeter** [comment]
Duplicate of https://github.com/datalust/nlog-targets-seq/issues/59#issuecomment-1137510375
fixed！

**Comment by gwnpeter** [comment]
Duplicate of https://github.com/datalust/nlog-targets-seq/issues/59#issuecomment-1137510375
fixed！

**Comment by gwnpeter** [comment]
fixed！

**Comment by gwnpeter** [comment]
close
