### ISSUE TITLE
Messages using composite formatting are not interpreted

### ISSUE THREAD

**Issue by dmontgomery** [datalust/nlog-targets-seq#67]
Hi,

I asked this question on SO, and thought I should repeat it here:

https://stackoverflow.com/questions/76665941/nlog-targets-seq-and-composite-formatting

Any advice would be appreciated.

**Comment by dmontgomery** [comment]
I withdraw my question.  It clearly is not caused by the SeqTarget class because this test works:

```
        [Fact]
        public void CompositeFormattingMessagesWork()
        {
            var evt = AssertValidJson(log => log.Info("A {0} and his {1}", "boy", "dog"));
            Assert.Equal("A boy and his dog", evt["@m"]);
        }
```

**Comment by snakefoot** [comment]
Could you update to [NLog.Targets.Seq v3.1.0-dev-00136](https://www.nuget.org/packages/NLog.Targets.Seq/3.1.0-dev-00136), and see if it resolves your issue ?

**Comment by snakefoot** [comment]
NLog.Targets.Seq v3.1.0 has been released: https://www.nuget.org/packages/NLog.Targets.Seq/3.1.0

**Comment by dmontgomery** [comment]
Thank you for the follow-up @snakefoot , but unfortunately the latest version did not change the behavior.

We're now requiring everyone to use `Logger.Error(e, e.Message)` instead of `Logger.Error(e)` for generic exception logging.

Also, I'm certainly not ruling out that we've got a bad NLog configuration somewhere in our pipeline...

**Comment by snakefoot** [comment]
So the use-case changed from the original issue. So it is about exception logging, where only logging single parameter.

Interesting why the internal NLog `ExceptionMessageFormatProvider` is not activated for `Logger.Error(ex)`.

Notice NLog v5 should improve the handling of `Logger.Error(ex)`. See also: https://github.com/NLog/NLog/issues/5272#issuecomment-1615869552

**Comment by dmontgomery** [comment]
You're correct @snakefoot.  My early search was focused on the composite messaging, but the 'final' problem became only unformatted exceptions.  Thanks for sharing the NLog issue.  Very helpful.
