### ISSUE TITLE
Arrays inside dicts?

### ISSUE THREAD

**Issue by chucker** [datalust/nlog-targets-seq#70]
I have an Seq target like so:

```xml
<targets>
    <target name="seq" xsi:type="BufferingWrapper" bufferSize="1000" flushTimeout="2000">
        <target xsi:type="Seq" serverUrl="https://ourServer" apiKey="asd" />
    </target>
</targets>

<rules>
    <logger name="*" minlevel="Trace" writeTo="seq" />
</rules>

<extensions>
    <add assembly="NLog.Targets.Seq" />
</extensions>
```

And I can push some additional scope properties:

```vb
logger.PushScopeProperty("ArrayTest", New Integer() {1, 2, 3})
logger.PushScopeProperty("DictTest", New Dictionary(Of String, Object) From {{"KeyWithArray", New Integer() {1, 2, 3}}, {"KeyWithString", "Hello"}})
```

Now, in the case of `ArrayTest` and `ArrayInDictTest`, Seq recognizes these as JSON. However, in the latter case, the array _inside_ the dictionary is treated as empty:

```
ArrayTest
[1, 2, 3]

DictTest
{
KeyWithArray: [],
KeyWithString: 'Hello'
}
```

Both keys are there, but only the string gets a value.

This is with target versions 2.1.0 and 3.0.0 on .NET 4.7.2, and Seq version 2023.4.10146.

(I'm not a 100% that this is on the target's end. However, I believe it works with the equivalent Serilog NuGet package.)

**Comment by snakefoot** [comment]
Maybe try to specify `MaxRecursionLimit="1"` like this:
```xml
<target xsi:type="Seq" serverUrl="https://ourServer" apiKey="asd" MaxRecursionLimit="1"  />
```

**Comment by chucker** [comment]
…oh, that makes sense. That indeed fixed it, thanks.
