### ISSUE TITLE
Destructuring `@` operator support

### ISSUE THREAD

**Issue by nblumhardt** [datalust/nlog-targets-seq#8]
The following should log structured data:

```csharp
logger.Info("Hello, {@User}", new User { Name = "Alice" });
```

While the example without `@` should log using `ToString()`:

```csharp
logger.Info("Hello, {User}", new User { Name = "Alice" });
```

At present, both will use `ToString`, although in both cases the value of the `A` property will be the `User` object.

**Comment by nblumhardt** [comment]
@304NotModified is there a way to detect the difference in these two cases apart from inspecting the `Hole` for `User`? Thanks!! :-)

**Comment by 304NotModified** [comment]
> At present, both will use ToString, although in both cases the value of the A property will be the User object.

That a bug I guess. `logger.Info("Hello, {@User}", new User { Name = "Alice" });`

should be

`Hello,  { Name = "Alice" }` ?

**Comment by nblumhardt** [comment]
I think (though would need to reexamine) that the formatting is okay; I'm mostly interested in how the target should determine to serialize `A` along with the JSON payload it's producing, rather than embed the value of `A` using `ToString()` (hope this makes sense!).

As far as I can tell, the only way to do it currently is iterate through the template and examine the holes, which should work, but it seems like there might be some more targeted API for it.

**Comment by 304NotModified** [comment]
> As far as I can tell, the only way to do it currently is iterate through the template and examine the holes, which should work, but it seems like there might be some more targeted API for it.

yes that's correct. I'm curious how the API would look like :)

**Comment by nblumhardt** [comment]
👍 thanks for the follow-up. The current method will work, although it'll be a little bit tricky to do 100% correctly. For example if `A` is marked with `@` in the template, but another component has (perhaps accidentally) overridden `A` by adding a property manually, we need to be sure not to attempt to serialize the value of the property, since the directive only applied to the original value of `A` that came in through `Parameters`.

One possible solution would be to perform a conversion when processing the template; for example, when adding `A` to the `Properties` collection, if the `@` is not present it would be converted immediately to a scalar value (perhaps with `ToString()`) so that the value of `A` in `Properties` is only a complex object when `@` is used.

This'd be different from how `Parameters` behaves, but since template binding is a new feature it wouldn't be a breaking change (as far as I can tell).

That way, to represent `Properties` in say, a JSON document, a target could reliably just JSON-serialize every value as-is, without worrying what the intention of the user was.

The downsides of this approach would be:

 * If the value has a format specifier, e.g. `{@A:000}`, then things get tricky (though I've never seen this used in practice - Serilog doesn't respect the format specifier in these cases)
 * Deciding on what constitutes a "scalar" value means some kind of heuristic or set of rules; Serilog considers strings, numerics and Booleans to be scalar (plus a few other types), but needs to provide a configuration option for users to declare other custom types as scalars

There are probably other (and better) ways to do this - I guess I'm just interested in how the responsibility for deciding whether a property should be serialized or `ToString()`ed could be taken on by the framework and kept out of the targets.

Interested to know your thoughts!

**Comment by 304NotModified** [comment]
> For example if A is marked with @ in the template, but another component has (perhaps accidentally) overridden A by adding a property manually, we need to be sure not to attempt to serialize the value of the property

Ah I see the case. 
What's going wrong here, except not getting the excepted result?

Another option is by not using `logEventInfo.Parameters` at all, but a new dictionary

> One possible solution would be to perform a conversion when processing the template; for example, when adding A to the Properties collection, if the @ is not present it would be converted immediately to a scalar value (perhaps with ToString()) so that the value of A in Properties is only a complex object when @ is used.

IMO a bit to much trick ;)

**Comment by nblumhardt** [comment]
> What's going wrong here, except not getting the excepted result?

Only that - not getting the expected result ;-)

I'll have a shot at doing it by iterating through the template so we can see what the code looks like. It may be fine for practical purposes.

Off-topic, but one thing that might be nice to extract from this sink is a new JSON formatter (a layout, perhaps?) that is aware of `@` and does the right thing. Unless there's one already implemented I should check out?

Thanks for all of the input.

**Comment by 304NotModified** [comment]
do you mean something like this? 

```
${event-properties:item=param1:jsonEncode=true}
```

**Comment by nblumhardt** [comment]
No, I was thinking more of something that would make it easy for JSON-based targets to carry everything from `Properties` serialized the right way. (The Seq, Splunk, Elasticsearch, CouchDB, RavenDB and many other Serilog sinks do this).

For example, if I log:

```csharp
logger.Info("Hello, {@User}", user);
```

Then one of those sinks would send a JSON document over the network with content like:

```json
{"@t":"2017-02-15...", ... "User":{"Name":"alice","Domain":"local"}}
```

While:

```csharp
logger.Info("Hello, {User}", user);
```

should just produce a `User` property with the to-string value:

```json
{"@t":"2017-02-15...", ... "User":"LOCAL\\alice"}
```

Each sink tends to have a unique JSON schema for things like timestamps, so there's not much common code there, but encoding a property value as JSON is such a common task that we have [`JsonValueFormatter` to do it](https://nblumhardt.com/2016/07/serilog-2-0-json-improvements/). The overall design would need to be different within NLog, but I think the same need will probably emerge.

**Comment by 304NotModified** [comment]
A will think about it. 

About the @ not used thing, I could change the implementation and interface of logeventinfo.properties. there I will record which capuretype is used and an user could change this when needed. 

AFAIK this could done backwards compatible. Would this work?

**Comment by 304NotModified** [comment]
Ps on mobile ;)

**Comment by nblumhardt** [comment]
That also sounds like a good option. I didn't suggest it because I hadn't thought through the backwards-compatibility part, but if it can be done it should cover it 👍

**Comment by nblumhardt** [comment]
It looks like `NLog.Targets.DefaultJsonSerializer` is the thing I've been looking for here. Will try to move the `JsonWriter` code over to it.
