### ISSUE TITLE
Mark  Seq.Client.NLog as deprecated and replaced by NLog.Targets.Seq

### ISSUE THREAD

**Issue by snakefoot** [datalust/nlog-targets-seq#81]
Maybe consider marking the nuget-package [Seq.Client.NLog](https://www.nuget.org/packages/Seq.Client.NLog) as deprecated, and redirect to [NLog.Targets.Seq](https://www.nuget.org/packages/NLog.Targets.Seq) ?

**Comment by nblumhardt** [comment]
Done! Thanks for spotting this, @snakefoot.
